base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  rolling_window: false
  resolution: 0.05
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  rolling_window: true
  resolution: 0.05
  width: 6.0
  height: 6.0
  footprint: [[-0.4, -0.4], [0.4, -0.4], [0.4, 0.4], [-0.4, 0.4]]
recovery_behavior_enabled: true